services:
  - type: web
    name: telegram-video-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: 8981877942:AAHvslByG-QQTnfHjURFRlmD1ygBXRBBe0o
        sync: false
