services:
  - type: web
    name: telegram-video-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: 8772426864:AAH_0Sj37SwBLLrEu9Gr9qkH5HdCirIqgwQ
        sync: false
