services:
  - type: web
    name: telegram-video-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: 7897954845:AAFUwELbooZnUyKH0mXL3NSgXCo8OExwXzs
        sync: false
